# Generated by Django 2.2.13 on 2021-03-04 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210304_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_faculty',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_student',
        ),
    ]
