# Generated by Django 2.2.13 on 2021-02-28 23:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210119_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abbrev', models.CharField(max_length=12)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='student',
            name='takenClass',
        ),
        migrations.AddField(
            model_name='faculty',
            name='posted_jobs',
            field=models.ManyToManyField(to='account.Job'),
        ),
        migrations.AddField(
            model_name='job',
            name='hourly_salary',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='job',
            name='hours_per_week',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='job',
            name='posted_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.RemoveField(
            model_name='student',
            name='applied_positions',
        ),
        migrations.AddField(
            model_name='student',
            name='applied_positions',
            field=models.ManyToManyField(to='account.Job'),
        ),
        migrations.AddField(
            model_name='student',
            name='course_taken',
            field=models.ManyToManyField(to='account.Course'),
        ),
    ]
