# Generated by Django 2.2.13 on 2021-03-04 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210304_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_faculty',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='account.Faculty'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_student',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='account.Student'),
        ),
    ]
