# Generated by Django 2.2.13 on 2021-03-03 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210228_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='name',
        ),
        migrations.RemoveField(
            model_name='job',
            name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Faculty'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Student'),
        ),
    ]
