# Generated by Django 2.2.13 on 2021-02-09 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_student_takenclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('abbrev', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='taken_class',
            field=models.ManyToManyField(to='account.Courses'),
        ),
    ]
