# Generated by Django 2.2.13 on 2021-03-04 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210304_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='grade',
            field=models.CharField(default='', max_length=3),
        ),
    ]
