# Generated by Django 2.2.13 on 2021-02-11 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210209_2227'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course',
        ),
        migrations.RemoveField(
            model_name='student',
            name='applied_positions',
        ),
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='student',
            name='taken_class',
        ),
        migrations.AlterField(
            model_name='student',
            name='GPA',
            field=models.FloatField(default=0),
        ),
    ]
