# Generated by Django 2.2.13 on 2021-03-04 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_course_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='course_req',
            field=models.ManyToManyField(to='account.Course'),
        ),
    ]
