# Generated by Django 2.2.13 on 2021-03-05 00:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_job_course_req'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='applicants',
            field=models.ManyToManyField(default=0, to='account.Student'),
        ),
        migrations.AlterField(
            model_name='job',
            name='course_req',
            field=models.ManyToManyField(default=0, to='account.Course'),
        ),
        migrations.AlterField(
            model_name='job',
            name='posted_date',
            field=models.DateField(verbose_name=datetime.date(2021, 3, 5)),
        ),
        migrations.AlterField(
            model_name='student',
            name='applied_positions',
            field=models.ManyToManyField(default=0, to='account.Job'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course_taken',
            field=models.ManyToManyField(default=0, to='account.Course'),
        ),
    ]
