# Generated by Django 2.2.13 on 2021-03-06 22:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20210305_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='courses_taught',
            field=models.ManyToManyField(default=0, to='account.Course'),
        ),
        migrations.AddField(
            model_name='student',
            name='resume_pdf',
            field=models.FileField(null=True, upload_to='pdf'),
        ),
        migrations.AddField(
            model_name='student',
            name='transcript',
            field=models.FileField(null=True, upload_to='pdf'),
        ),
        migrations.AlterField(
            model_name='job',
            name='posted_date',
            field=models.DateField(verbose_name=datetime.date(2021, 3, 6)),
        ),
    ]
