# Generated by Django 2.2.13 on 2021-03-06 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20210306_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='applied_positions',
            field=models.ManyToManyField(default=0, null=True, to='account.Job'),
        ),
    ]
