# Generated by Django 2.2.13 on 2021-03-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20210306_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='applied_positions',
            field=models.ManyToManyField(blank=True, default=0, to='account.Job'),
        ),
    ]
