# Generated by Django 2.2.13 on 2021-03-06 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20210306_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='resume_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf'),
        ),
        migrations.AlterField(
            model_name='student',
            name='transcript',
            field=models.FileField(blank=True, null=True, upload_to='pdf'),
        ),
    ]
