#!/bin/bash

RED='\033[1;31m'
PYTHON="python3"
PIP="pip3"

if ! $PYTHON -c "import sys; sys.exit(sys.prefix != sys.base_prefix)"; then
    echo -e ""
    echo -e "${RED}A python virtual enviroment is already active. Please 'deactivate' first."
    exit 1
fi

echo -e "Installing virtualenv"

$PIP install virtualenv

if ! virtualenv pyvenv; then
echo -e "${RED}virtualenv failed."
exit 1
fi

if ! source pyvenv/bin/activate; then
    echo -e "${RED}sourcing failed."
    exit 1
fi



$PIP install -r requirements.txt

